name: januaryfredericks
favicon: null
layout_spectrum: 0.3902843117248267
typography_spectrum: 0.8863191388081759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9fafc'
    - '#050503'
    - '#a0a59c'
    - '#292a1c'
    - '#636456'
  brandStrength: 0.1875
  lightness: 0.052864510333165526
  saturation: 0.0617685723118484
  rhythmicContrast: 0.6839754399843514
purpose: []
